### ISSUE TITLE
python script improvement

### ISSUE THREAD

**Issue by telendt** [lorca/flat_file_benchmark#2]
```
#!/usr/bin/env python
import sys
import csv

with open(sys.argv[1]) as f:
    rows = list(csv.reader(f, "excel-tab"))
    print ",".join(rows[1])
```

**Comment by lorca** [comment]
hey tried it out, slight difference.  though you made me think of a difference enhancement to my example which is to convert the the row into a tuple before adding it to rows.

https://github.com/lorca/flat_file_benchmark/blob/master/pics/benchmark.png
